// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserSaver is an autogenerated mock type for the UserSaver type
type UserSaver struct {
	mock.Mock
}

type UserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSaver) EXPECT() *UserSaver_Expecter {
	return &UserSaver_Expecter{mock: &_m.Mock}
}

// SaveUser provides a mock function with given fields: ctx, name, username, PassHash
func (_m *UserSaver) SaveUser(ctx context.Context, name string, username string, PassHash []byte) (int, error) {
	ret := _m.Called(ctx, name, username, PassHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) (int, error)); ok {
		return rf(ctx, name, username, PassHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) int); ok {
		r0 = rf(ctx, name, username, PassHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = rf(ctx, name, username, PassHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSaver_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type UserSaver_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - username string
//   - PassHash []byte
func (_e *UserSaver_Expecter) SaveUser(ctx interface{}, name interface{}, username interface{}, PassHash interface{}) *UserSaver_SaveUser_Call {
	return &UserSaver_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, name, username, PassHash)}
}

func (_c *UserSaver_SaveUser_Call) Run(run func(ctx context.Context, name string, username string, PassHash []byte)) *UserSaver_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *UserSaver_SaveUser_Call) Return(uid int, err error) *UserSaver_SaveUser_Call {
	_c.Call.Return(uid, err)
	return _c
}

func (_c *UserSaver_SaveUser_Call) RunAndReturn(run func(context.Context, string, string, []byte) (int, error)) *UserSaver_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserSaver creates a new instance of UserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSaver {
	mock := &UserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
