// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	models "auth/internal/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserProvider is an autogenerated mock type for the UserProvider type
type UserProvider struct {
	mock.Mock
}

type UserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *UserProvider) EXPECT() *UserProvider_Expecter {
	return &UserProvider_Expecter{mock: &_m.Mock}
}

// User provides a mock function with given fields: ctx, username
func (_m *UserProvider) User(ctx context.Context, username string) (models.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProvider_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type UserProvider_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserProvider_Expecter) User(ctx interface{}, username interface{}) *UserProvider_User_Call {
	return &UserProvider_User_Call{Call: _e.mock.On("User", ctx, username)}
}

func (_c *UserProvider_User_Call) Run(run func(ctx context.Context, username string)) *UserProvider_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserProvider_User_Call) Return(_a0 models.User, _a1 error) *UserProvider_User_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProvider_User_Call) RunAndReturn(run func(context.Context, string) (models.User, error)) *UserProvider_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserProvider creates a new instance of UserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProvider {
	mock := &UserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
